add filter for upgrade workflow

diff --git a/.github/workflows/upgrade.yml b/.github/workflows/upgrade.yml
--- a/.github/workflows/upgrade.yml
+++ b/.github/workflows/upgrade.yml
@@ -34,4 +34,12 @@ jobs:
           git config --global user.name ${{ github.actor }}
 
       - name: 🍏 Upgrade dependencies
-        run: npm run upgrade -- --MODULE=${{ github.event.inputs.filter }}
+        env:
+          FILTER: ${{ github.event.inputs.filter }}
+        shell: bash {0}
+        run: |
+          if [[ -n "$FILTER" && ! "$FILTER" =~ ^@paypal/ ]]; then
+            echo "Error: Only @paypal packages are allowed."
+            exit 1
+          fi
+          npm run upgrade -- --MODULE="${FILTER}"
